CREATE DATABASE QLBAO
GO
USE QLBAO
-- 1. Tạo bảng và ràng buộc cần thiết
CREATE TABLE HOINGHI
(
    MAHOINGHI NVARCHAR(10) NOT NULL,
    QUOCGIA NVARCHAR(20) NOT NULL,
    TENHOINGHI NVARCHAR(50) UNIQUE,
    NAMTHANHLAP INT,
    NHAXUATBAN NVARCHAR(50),
    PRIMARY KEY (MAHOINGHI)
)

CREATE TABLE TOCHUC
(
    HOINGHI NVARCHAR(10) NOT NULL,
    NAMTOCHUC INT NOT NULL,
    DIADIEM NVARCHAR(50),
    BAIBAOTIEUBIEU INT,
    PRIMARY KEY (HOINGHI, NAMTOCHUC)
)

CREATE TABLE BAIBAO
(
    STT INT NOT NULL,
    HOINGHI NVARCHAR(10) NOT NULL,
    NAMTOCHUC INT NOT NULL,
    LOAIBAIBAO NVARCHAR(15),
    CHUDE NVARCHAR(20),
    PRIMARY KEY (STT, HOINGHI, NAMTOCHUC)
)

ALTER TABLE TOCHUC
ADD CONSTRAINT FK_TOCHUC_HOINGHI
FOREIGN KEY(HOINGHI)
REFERENCES HOINGHI(MAHOINGHI)

ALTER TABLE BAIBAO
ADD CONSTRAINT FK_BAIBAO_TOCHUC
FOREIGN KEY (HOINGHI, NAMTOCHUC)
REFERENCES TOCHUC(HOINGHI, NAMTOCHUC)

ALTER TABLE TOCHUC
ADD CONSTRAINT FK_TOCHUC_BAIBAO
FOREIGN KEY (BAIBAOTIEUBIEU, HOINGHI, NAMTOCHUC)
REFERENCES BAIBAO(STT, HOINGHI, NAMTOCHUC)

-- 2. Nhập các dòng dữ liệu bên dưới vào các bảng tương ứng
INSERT INTO HOINGHI(MAHOINGHI, QUOCGIA, TENHOINGHI, NAMTHANHLAP, NHAXUATBAN) VALUES
(N'CITA', N'Việt Nam', N'Công nghệ thông tin và ứng dụng', 2023, N'Giáo dục'),
(N'KES', N'Hoa Kỳ', N'Tri thức và dữ liệu', 2022, N'IEEE')

INSERT INTO TOCHUC(HOINGHI, NAMTOCHUC, DIADIEM) VALUES
(N'CITA', 2023, N'Đà Nẵng, Việt Nam'),
(N'KES', 2022, N'Tokyo, Nhật Bản'),
(N'KES', 2023, N'Paris, Pháp')

INSERT INTO BAIBAO(STT, HOINGHI, NAMTOCHUC, LOAIBAIBAO, CHUDE) VALUES
(1, N'CITA', 2023, N'Toàn văn', N'Ứng dụng'),
(2, N'CITA', 2023, N'Tóm tắt', N'Nghiên cứu'),
(1, N'KES', 2022, N'Tóm tắt', N'Nghiên cứu'),
(1, N'KES', 2023, N'Toàn văn', N'Ứng dụng'),
(2, N'KES', 2023, N'Toàn văn', N'Ứng dụng')

UPDATE TOCHUC SET BAIBAOTIEUBIEU = 2 WHERE HOINGHI = N'CITA' AND NAMTOCHUC = 2023
UPDATE TOCHUC SET BAIBAOTIEUBIEU = 1 WHERE HOINGHI = N'KES' AND NAMTOCHUC = 2022
UPDATE TOCHUC SET BAIBAOTIEUBIEU = 2 WHERE HOINGHI = N'KES' AND NAMTOCHUC = 2023
-- 3. Cho địa điểm tổ chức hội nghị "Tri thức và dữ liệu" năm 2023
SELECT TC.DIADIEM
FROM HOINGHI HN, TOCHUC TC
WHERE HN.MAHOINGHI = TC.HOINGHI AND HN.TENHOINGHI = N'Tri thức và dữ liệu' AND TC.NAMTOCHUC = 2023

-- 4. Cho danh sách tên hội nghị và tên quốc gia của các hội nghị đã từng được
-- tổ chức tại Nhật có bài báo tiêu biểu thuộc về chủ đề “Nghiên cứu” và không có
-- bài báo toàn văn nào thuộc chủ đề “Ứng dụng”.
SELECT HN.MAHOINGHI 'Mã hội nghị', HN.TENHOINGHI 'Tên hội nghị'
FROM BAIBAO BB, HOINGHI HN, TOCHUC TC
WHERE BB.HOINGHI = TC.HOINGHI AND TC.HOINGHI = HN.MAHOINGHI AND BB.NAMTOCHUC = TC.NAMTOCHUC
      AND TC.DIADIEM LIKE N'%Nhật%' AND BB.CHUDE = N'Nghiên cứu'
EXCEPT
SELECT HN.MAHOINGHI 'Mã hội nghị', HN.TENHOINGHI 'Tên hội nghị'
FROM BAIBAO BB, HOINGHI HN, TOCHUC TC
WHERE BB.HOINGHI = TC.HOINGHI AND TC.HOINGHI = HN.MAHOINGHI AND BB.NAMTOCHUC = TC.NAMTOCHUC
      AND TC.DIADIEM LIKE N'%Nhật%' AND BB.CHUDE = N'Ứng dụng' AND BB.LOAIBAIBAO = N'Toàn văn'

-- 5. Cho mã hội nghị, tên hội nghị, số lần hội nghị được tổ chức và số lượng bài báo cho từng lần tổ chức.
SELECT HN.MAHOINGHI 'Mã hội nghị', HN.TENHOINGHI 'Tên hội nghị', COUNT(TC.HOINGHI) 'Số lần tổ chức hội nghị', COUNT(BB.HOINGHI) "Số bài báo được công bố" 
FROM HOINGHI HN, BAIBAO BB, TOCHUC TC
WHERE HN.MAHOINGHI = TC.HOINGHI AND TC.HOINGHI = BB.HOINGHI AND BB.NAMTOCHUC = TC.NAMTOCHUC
GROUP BY HN.MAHOINGHI, HN.TENHOINGHI
