--Q58 Cho biết tên giáo viên nào mà tham gia đề tài đủ tất cả các chủ đề.
SELECT DISTINCT GV1.HOTEN
FROM GIAOVIEN GV1
JOIN THAMGIADT TG ON TG.MAGV = GV1.MAGV
WHERE NOT EXISTS (
    SELECT CD1.MACD
    FROM CHUDE CD1
    WHERE NOT EXISTS (
        SELECT DT1.MACD
        FROM DETAI DT1
        JOIN THAMGIADT TG1 ON TG1.MADT = DT1.MADT
        WHERE TG1.MAGV = GV1.MAGV
          AND DT1.MACD = CD1.MACD
    )
)
SELECT GV1.HOTEN
FROM GIAOVIEN GV1
WHERE NOT EXISTS (
    SELECT CD1.MACD
    FROM CHUDE CD1
    EXCEPT
    SELECT DT1.MACD
    FROM DETAI DT1
    JOIN THAMGIADT TG1 ON TG1.MADT = DT1.MADT
    WHERE TG1.MAGV = GV1.MAGV
)

SELECT GV1.HOTEN
FROM GIAOVIEN GV1
JOIN THAMGIADT TG ON TG.MAGV = GV1.MAGV
JOIN DETAI DT ON DT.MADT = TG.MADT
GROUP BY GV1.MAGV, GV1.HOTEN
HAVING COUNT(DISTINCT DT.MACD) = (
    SELECT COUNT(MACD)
    FROM CHUDE
)


--Q59. Cho biết tên đề tài nào mà được tất cả các giáo viên của bộ môn HTTT tham gia.
SELECT DT1.TENDT
FROM DETAI DT1
WHERE NOT EXISTS(
	SELECT GV1.MAGV
	FROM GIAOVIEN GV1
	WHERE GV1.MABM = 'HTTT'
	EXCEPT
	(
		SELECT THAMGIADT.MAGV
		FROM THAMGIADT
		WHERE DT1.MADT = THAMGIADT.MADT
	)
)

SELECT DT1.TENDT
FROM DETAI DT1
WHERE NOT EXISTS(
	SELECT GV1.MAGV
	FROM GIAOVIEN GV1
	WHERE GV1.MABM = 'HTTT'
	AND NOT EXISTS(
		SELECT THAMGIADT.MAGV
		FROM THAMGIADT
		WHERE GV1.MAGV = THAMGIADT.MAGV AND THAMGIADT.MADT = DT1.MADT
	)
)

SELECT DT1.TENDT
FROM DETAI DT1
JOIN THAMGIADT TG ON TG.MADT = DT1.MADT
JOIN GIAOVIEN GV1 ON GV1.MAGV = TG.MAGV
WHERE GV1.MABM = 'HTTT'
GROUP BY DT1.TENDT
HAVING COUNT(DISTINCT GV1.MAGV) = (
	SELECT COUNT(MAGV)
	FROM GIAOVIEN 
	WHERE MABM = 'HTTT'
)
--Q60. Cho biết tên đề tài có tất cả giảng viên bộ môn “Hệ thống thông tin” tham gia
SELECT  DT1.TENDT
FROM DETAI DT1
WHERE NOT EXISTS(
	SELECT GV1.MAGV
	FROM GIAOVIEN GV1
	JOIN BOMON BM1 ON GV1.MABM =  BM1.MABM
	WHERE BM1.TENBM = N'Hệ thống thông tin'
	EXCEPT
	SELECT THAMGIADT.MAGV
	FROM THAMGIADT
	WHERE DT1.MADT = THAMGIADT.MADT
) 	AND EXISTS (
		SELECT GV2.MAGV
		FROM GIAOVIEN GV2
		JOIN BOMON BM2 ON GV2.MABM =  BM2.MABM
		WHERE BM2.TENBM = N'Hệ thống thông tin'
)

SELECT  DT1.TENDT
FROM DETAI DT1
WHERE NOT EXISTS(
	SELECT GV1.MAGV
	FROM GIAOVIEN GV1
	JOIN BOMON BM1 ON GV1.MABM =  BM1.MABM
	WHERE BM1.TENBM = N'Hệ thống thông tin'
	AND NOT EXISTS(
		SELECT THAMGIADT.MAGV
		FROM THAMGIADT
		WHERE DT1.MADT = THAMGIADT.MADT AND THAMGIADT.MAGV = GV1.MAGV
	)
)

SELECT DT1.TENDT
FROM DETAI DT1
JOIN THAMGIADT TG1 ON TG1.MADT = DT1.MADT
JOIN GIAOVIEN GV ON GV.MAGV = TG1.MAGV
JOIN BOMON BM ON GV.MABM = BM.MABM
WHERE BM.TENBM = N'Hệ thống thông tin'
GROUP BY DT1.TENDT
HAVING COUNT(DISTINCT GV.MAGV) = (
    SELECT COUNT(GV1.MAGV)
    FROM GIAOVIEN GV1
    JOIN BOMON BM1 ON GV1.MABM = BM1.MABM
    WHERE BM1.TENBM = N'Hệ thống thông tin'
)

--Q61. Cho biết giáo viên nào đã tham gia tất cả các đề tài có mã chủ đề là QLGD.
SELECT GV1.MAGV, GV1.HOTEN
FROM GIAOVIEN GV1
where not exists (
	select dt.MADT
	from DETAI dt
	where dt.MACD = N'QLGD'
	except 
	SELECT THAMGIADT.MADT
	FROM THAMGIADT
	where GV1.MAGV = THAMGIADT.MAGV
)

SELECT GV1.MAGV, GV1.HOTEN
FROM GIAOVIEN GV1
WHERE NOT EXISTS(
	SELECT DT.MADT
	FROM DETAI DT
	WHERE DT.MACD = N'QLGD' AND NOT EXISTS(
		SELECT THAMGIA.MADT
		FROM THAMGIADT THAMGIA
		WHERE THAMGIA.MADT = DT.MADT AND GV1.MAGV = THAMGIA.MAGV
	)
)

SELECT GV1.MAGV, GV1.HOTEN
FROM GIAOVIEN GV1
JOIN THAMGIADT TG ON GV1.MAGV = TG.MAGV
JOIN DETAI DT ON DT.MADT = TG.MADT
WHERE DT.MACD = N'QLGD'
GROUP BY GV1.MAGV, GV1.HOTEN
HAVING COUNT(DISTINCT TG.MADT) = (SELECT COUNT(MADT) FROM DETAI WHERE DETAI.MACD = N'QLGD')
--Q62. Cho biết tên giáo viên nào tham gia tất cả các đề tài mà giáo viên Trần Trà Hương đã tham gia.
SELECT GV1.MAGV, GV1.HOTEN
FROM GIAOVIEN GV1
WHERE NOT EXISTS (
	SELECT TG.MADT
	FROM THAMGIADT TG
	JOIN GIAOVIEN GV2 ON GV2.MAGV = TG.MAGV
	WHERE GV2.HOTEN = N'Trần Trà Hương'
	EXCEPT
	SELECT TG1.MADT
	FROM THAMGIADT TG1
	WHERE TG1.MAGV = GV1.MAGV
)
AND GV1.HOTEN != N'Trần Trà Hương'

SELECT GV1.MAGV, GV1.HOTEN
FROM GIAOVIEN GV1
WHERE NOT EXISTS(
	SELECT TG.MADT
	FROM THAMGIADT TG
	JOIN GIAOVIEN GV2 ON GV2.MAGV = TG.MAGV
	WHERE GV2.HOTEN = N'Trần Trà Hương' AND NOT EXISTS(
		SELECT TG2.MADT
		FROM THAMGIADT TG2
		WHERE TG2.MADT = TG.MADT AND TG2.MAGV = GV1.MAGV
	)
)
AND GV1.HOTEN != N'Trần Trà Hương'

SELECT GV1.MAGV, GV1.HOTEN
FROM GIAOVIEN GV1
JOIN THAMGIADT TG1 ON TG1.MAGV = GV1.MAGV
WHERE GV1.HOTEN != N'Trần Trà Hương'
GROUP BY GV1.MAGV, GV1.HOTEN
HAVING COUNT(DISTINCT TG1.MADT) >= (
    SELECT COUNT(DISTINCT TG4.MADT)
    FROM THAMGIADT TG4
    JOIN GIAOVIEN GV4 ON TG4.MAGV = GV4.MAGV
    WHERE GV4.HOTEN = N'Trần Trà Hương'
)
AND NOT EXISTS (
    SELECT TG2.MADT 
    FROM THAMGIADT TG2
    JOIN GIAOVIEN GV2 ON GV2.MAGV = TG2.MAGV
    WHERE GV2.HOTEN = N'Trần Trà Hương'
    EXCEPT
    SELECT TG1.MADT
    FROM THAMGIADT TG1
    WHERE TG1.MAGV = GV1.MAGV
)
--Q63. Cho biết tên đề tài nào mà được tất cả các giáo viên của bộ môn Hóa Hữu Cơ tham gia.
SELECT  DT1.TENDT
FROM DETAI DT1
WHERE NOT EXISTS(
	SELECT GV1.MAGV
	FROM GIAOVIEN GV1
	JOIN BOMON BM1 ON GV1.MABM =  BM1.MABM
	WHERE BM1.TENBM = N'Hóa Hữu Cơ'
	EXCEPT
	SELECT THAMGIADT.MAGV
	FROM THAMGIADT
	WHERE DT1.MADT = THAMGIADT.MADT
) 	AND EXISTS (
		SELECT GV2.MAGV
		FROM GIAOVIEN GV2
		JOIN BOMON BM2 ON GV2.MABM =  BM2.MABM
		WHERE BM2.TENBM = N'Hóa Hữu Cơ'
)

SELECT  DT1.TENDT
FROM DETAI DT1
WHERE NOT EXISTS(
	SELECT GV1.MAGV
	FROM GIAOVIEN GV1
	JOIN BOMON BM1 ON GV1.MABM =  BM1.MABM
	WHERE BM1.TENBM = N'Hóa Hữu Cơ'
	AND NOT EXISTS(
		SELECT THAMGIADT.MAGV
		FROM THAMGIADT
		WHERE DT1.MADT = THAMGIADT.MADT AND THAMGIADT.MAGV = GV1.MAGV
	)
)

SELECT DT1.TENDT
FROM DETAI DT1
JOIN THAMGIADT TG1 ON TG1.MADT = DT1.MADT
JOIN GIAOVIEN GV ON GV.MAGV = TG1.MAGV
JOIN BOMON BM ON GV.MABM = BM.MABM
WHERE BM.TENBM = N'Hóa Hữu Cơ'
GROUP BY DT1.TENDT
HAVING COUNT(DISTINCT GV.MAGV) = (
    SELECT COUNT(GV1.MAGV)
    FROM GIAOVIEN GV1
    JOIN BOMON BM1 ON GV1.MABM = BM1.MABM
    WHERE BM1.TENBM = N'Hóa Hữu Cơ'
)

--Q64. Cho biết tên giáo viên nào mà tham gia tất cả các công việc của đề tài 006.
SELECT GV1.HOTEN
FROM GIAOVIEN GV1
WHERE NOT EXISTS (
	SELECT CV.SOTT
	FROM CONGVIEC CV
	WHERE CV.MADT = '006' AND NOT EXISTS(
		SELECT THAMGIADT.STT
		FROM THAMGIADT
		WHERE THAMGIADT.MADT ='006' AND CV.SOTT = THAMGIADT.STT AND THAMGIADT.MAGV = GV1.MAGV
	)
)

SELECT GV1.HOTEN
FROM GIAOVIEN GV1
WHERE NOT EXISTS (
	SELECT CV.SOTT
	FROM CONGVIEC CV
	WHERE CV.MADT = '006'
	EXCEPT
	SELECT THAMGIADT.STT
	FROM THAMGIADT
	WHERE THAMGIADT.MAGV = GV1.MAGV AND THAMGIADT.MADT = '006'
)

SELECT GV1.HOTEN
FROM GIAOVIEN GV1
JOIN THAMGIADT ON THAMGIADT.MAGV = GV1.MAGV
JOIN CONGVIEC ON CONGVIEC.MADT = THAMGIADT.MADT
WHERE CONGVIEC.MADT = '006'
GROUP BY GV1.HOTEN
HAVING COUNT(DISTINCT THAMGIADT.STT) = (SELECT COUNT(DISTINCT SOTT) FROM CONGVIEC WHERE CONGVIEC.MADT = '006')
--Q65. Cho biết giáo viên nào đã tham gia tất cả các đề tài của chủ đề Ứng dụng công nghệ.
SELECT GV1.MAGV, GV1.HOTEN
FROM GIAOVIEN GV1
WHERE NOT EXISTS (
    SELECT DT.MADT
    FROM DETAI DT
    WHERE DT.MACD = (SELECT MACD FROM CHUDE WHERE TENCD = N'Ứng dụng công nghệ')
    EXCEPT
    SELECT TG.MADT
    FROM THAMGIADT TG
    WHERE TG.MAGV = GV1.MAGV
);

SELECT GV1.MAGV, GV1.HOTEN
FROM GIAOVIEN GV1
WHERE NOT EXISTS(
	SELECT DT.MADT
	FROM DETAI DT
	WHERE DT.MACD = (SELECT MACD FROM CHUDE WHERE TENCD = N'Ứng dụng công nghệ') AND NOT EXISTS(
		SELECT THAMGIA.MADT
		FROM THAMGIADT THAMGIA
		WHERE THAMGIA.MADT = DT.MADT AND GV1.MAGV = THAMGIA.MAGV
	)
)

SELECT GV1.MAGV, GV1.HOTEN
FROM GIAOVIEN GV1
JOIN THAMGIADT TG ON GV1.MAGV = TG.MAGV
JOIN DETAI DT ON DT.MADT = TG.MADT
WHERE DT.MACD = (SELECT MACD FROM CHUDE WHERE TENCD = N'Ứng dụng công nghệ')
GROUP BY GV1.MAGV, GV1.HOTEN
HAVING COUNT(DISTINCT TG.MADT) = (SELECT COUNT(MADT) FROM DETAI WHERE DETAI.MACD = (SELECT MACD FROM CHUDE WHERE TENCD = N'Ứng dụng công nghệ'))
--Q66. Cho biết tên giáo viên nào đã tham gia tất cả các đề tài của do Trần Trà Hương làm chủ nhiệm.
SELECT GV1.HOTEN
FROM GIAOVIEN GV1
WHERE NOT EXISTS (
	SELECT DETAI.MADT
	FROM DETAI
	JOIN GIAOVIEN GV2 ON GV2.MAGV = DETAI.GVCNDT
	WHERE GV2.HOTEN = N'Trần Trà Hương'
	EXCEPT
	SELECT THAMGIADT.MADT
	FROM THAMGIADT
	WHERE THAMGIADT.MAGV = GV1.MAGV
)

SELECT GV1.HOTEN
FROM GIAOVIEN GV1
WHERE NOT EXISTS (
	SELECT DETAI.MADT
	FROM DETAI
	JOIN GIAOVIEN GV2 ON GV2.MAGV = DETAI.GVCNDT
	WHERE GV2.HOTEN = N'Trần Trà Hương'
	AND NOT EXISTS(
		SELECT THAMGIADT.MADT
		FROM THAMGIADT
		WHERE THAMGIADT.MAGV = GV1.MAGV AND DETAI.MADT = THAMGIADT.MADT
	)
)

SELECT GV1.MAGV, GV1.HOTEN
FROM GIAOVIEN GV1
JOIN THAMGIADT TG ON GV1.MAGV = TG.MAGV
JOIN DETAI ON DETAI.MADT = TG.MADT
--WHERE DETAI.GVCNDT = (SELECT MAGV FROM GIAOVIEN WHERE GIAOVIEN.HOTEN = N'Trần Trà Hương')
GROUP BY GV1.MAGV, GV1.HOTEN
HAVING COUNT(DISTINCT TG.MADT) = (
	SELECT COUNT(MADT) 
	FROM DETAI
	JOIN GIAOVIEN GV2 ON GV2.MAGV = DETAI.GVCNDT
	WHERE GV2.HOTEN = N'Trần Trà Hương'
)
--Q67. Cho biết tên đề tài nào mà được tất cả các giáo viên của khoa CNTT tham gia.
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS(
	SELECT GV1.MAGV
	FROM GIAOVIEN GV1
	JOIN BOMON BM1 ON BM1.MABM =  GV1.MABM
	JOIN KHOA KH ON KH.MAKHOA = BM1.MAKHOA
	WHERE KH.MAKHOA = 'CNTT'
	EXCEPT
	SELECT THAMGIADT.MAGV
	FROM THAMGIADT
	WHERE THAMGIADT.MADT = DT.MADT
) AND EXISTS (
	SELECT GV2.MAGV
	FROM GIAOVIEN GV2
	JOIN BOMON BM2 ON BM2.MABM =  GV2.MABM
	JOIN KHOA KH2 ON KH2.MAKHOA = BM2.MAKHOA
	WHERE KH2.MAKHOA = 'CNTT'
)

SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS (
	SELECT GV1.MAGV
	FROM GIAOVIEN GV1
	JOIN BOMON BM1 ON BM1.MABM = GV1.MABM
	JOIN KHOA KH1 ON KH1.MAKHOA =  BM1.MAKHOA
	WHERE KH1.MAKHOA = 'CNTT' AND NOT EXISTS (
		SELECT THAMGIADT.MAGV
		FROM THAMGIADT
		WHERE THAMGIADT.MAGV = GV1.MAGV AND THAMGIADT.MADT =  DT.MADT
	)
)

SELECT TG.MADT, DT.TENDT
FROM THAMGIADT TG
JOIN DETAI DT ON TG.MADT = DT.MADT
JOIN GIAOVIEN GV ON TG.MAGV = GV.MAGV
JOIN BOMON BM ON GV.MABM = BM.MABM
JOIN KHOA KH ON BM.MAKHOA = KH.MAKHOA
WHERE KH.MAKHOA = 'CNTT'
GROUP BY TG.MADT, DT.TENDT
HAVING COUNT(DISTINCT GV.MAGV) = (
    SELECT COUNT(DISTINCT GV1.MAGV)
    FROM GIAOVIEN GV1
    JOIN BOMON BM1 ON GV1.MABM = BM1.MABM
    JOIN KHOA KH1 ON BM1.MAKHOA = KH1.MAKHOA
    WHERE KH1.MAKHOA = 'CNTT'
)
--Q68. Cho biết tên giáo viên nào mà tham gia tất cả các công việc của đề tài Nghiên cứu tế bào gốc.
SELECT GV1.MAGV, GV1.HOTEN
FROM GIAOVIEN GV1
WHERE NOT EXISTS (
	SELECT CV.SOTT
	FROM CONGVIEC CV
	JOIN DETAI DT ON DT.MADT = CV.MADT
	WHERE DT.TENDT = N'Nghiên cứu tế bào gốc'
	EXCEPT
	SELECT THAMGIADT.STT
	FROM THAMGIADT
	WHERE THAMGIADT.MAGV = GV1.MAGV AND THAMGIADT.MADT = (select MADT FROM DETAI WHERE DETAI.TENDT = N'Nghiên cứu tế bào gốc')
)

SELECT GV1.MAGV, GV1.HOTEN
FROM GIAOVIEN GV1
WHERE NOT EXISTS (
	SELECT CV.SOTT
	FROM CONGVIEC CV
	JOIN DETAI DT ON DT.MADT = CV.MADT
	WHERE DT.TENDT = N'Nghiên cứu tế bào gốc'
	AND NOT EXISTS (
		SELECT THAMGIADT.STT
		FROM THAMGIADT
		WHERE THAMGIADT.MAGV = GV1.MAGV AND CV.SOTT = THAMGIADT.STT AND THAMGIADT.MADT = (select MADT FROM DETAI WHERE DETAI.TENDT = N'Nghiên cứu tế bào gốc')
	)
)

SELECT GV1.MAGV, GV1.HOTEN
FROM GIAOVIEN GV1
JOIN THAMGIADT TG ON TG.MAGV = GV1.MAGV
WHERE TG.MADT = (SELECT MADT FROM DETAI WHERE TENDT = N'Nghiên cứu tế bào gốc')
GROUP BY GV1.MAGV, GV1.HOTEN
HAVING COUNT(DISTINCT TG.STT) = (
    SELECT COUNT(SOTT)
    FROM CONGVIEC CV
    JOIN DETAI DT ON DT.MADT = CV.MADT
    WHERE DT.TENDT = N'Nghiên cứu tế bào gốc'
)
--Q69. Tìm tên các giáo viên được phân công làm tất cả các đề tài có kinh phí trên 100 triệu?
SELECT GV1.MAGV, GV1.HOTEN
FROM GIAOVIEN GV1
WHERE NOT EXISTS (
	SELECT DT.MADT
	FROM DETAI DT
	WHERE DT.KINHPHI > 100.0
	EXCEPT
	SELECT THAMGIADT.MADT
	FROM THAMGIADT
	WHERE THAMGIADT.MAGV = GV1.MAGV
)

SELECT GV1.MAGV, GV1.HOTEN
FROM GIAOVIEN GV1
WHERE NOT EXISTS(
	SELECT DT.MADT
	FROM DETAI DT
	WHERE DT.KINHPHI > 100.0 AND NOT EXISTS(
		SELECT THAMGIADT.MADT
		FROM THAMGIADT
		WHERE THAMGIADT.MAGV = GV1.MAGV	AND THAMGIADT.MADT = DT.MADT
	)
)

SELECT GV1.MAGV, GV1.HOTEN
FROM GIAOVIEN GV1
JOIN THAMGIADT TG ON GV1.MAGV = TG.MAGV
JOIN DETAI DT ON DT.MADT = TG.MADT
WHERE DT.KINHPHI > 100.0
GROUP BY GV1.MAGV, GV1.HOTEN
HAVING COUNT(DISTINCT TG.MADT) = (
	SELECT COUNT(DISTINCT DT.MADT)
	FROM DETAI DT
	WHERE DT.KINHPHI > 100.0
)
--Q70. Cho biết tên đề tài nào mà được tất cả các giáo viên của khoa Sinh Học tham gia.
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS(
	SELECT GV1.MAGV
	FROM GIAOVIEN GV1
	JOIN BOMON BM1 ON BM1.MABM =  GV1.MABM
	JOIN KHOA KH ON KH.MAKHOA = BM1.MAKHOA
	WHERE KH.TENKHOA = N'Sinh Học'
	EXCEPT
	SELECT THAMGIADT.MAGV
	FROM THAMGIADT
	WHERE THAMGIADT.MADT = DT.MADT
) AND EXISTS (
	SELECT GV2.MAGV
	FROM GIAOVIEN GV2
	JOIN BOMON BM2 ON BM2.MABM =  GV2.MABM
	JOIN KHOA KH2 ON KH2.MAKHOA = BM2.MAKHOA
	WHERE KH2.TENKHOA = N'Sinh Học'
)

SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS (
	SELECT GV1.MAGV
	FROM GIAOVIEN GV1
	JOIN BOMON BM1 ON BM1.MABM = GV1.MABM
	JOIN KHOA KH1 ON KH1.MAKHOA =  BM1.MAKHOA
	WHERE KH1.TENKHOA = N'Sinh Học' AND NOT EXISTS (
		SELECT THAMGIADT.MAGV
		FROM THAMGIADT
		WHERE THAMGIADT.MAGV = GV1.MAGV AND THAMGIADT.MADT =  DT.MADT
	)
)

SELECT DT.TENDT
FROM THAMGIADT TG
JOIN DETAI DT ON TG.MADT = DT.MADT
JOIN GIAOVIEN GV ON TG.MAGV = GV.MAGV
JOIN BOMON BM ON GV.MABM = BM.MABM
JOIN KHOA KH ON BM.MAKHOA = KH.MAKHOA
WHERE KH.TENKHOA = N'Sinh Học'
GROUP BY DT.TENDT
HAVING COUNT(DISTINCT GV.MAGV) = (
    SELECT COUNT(DISTINCT GV1.MAGV)
    FROM GIAOVIEN GV1
    JOIN BOMON BM1 ON GV1.MABM = BM1.MABM
    JOIN KHOA KH1 ON BM1.MAKHOA = KH1.MAKHOA
    WHERE KH1.TENKHOA = N'Sinh Học'
)
--Q71. Cho biết mã số, họ tên, ngày sinh của giáo viên tham gia tất cả các công việc của đề tài “Ứng dụng hóa học xanh”.
SELECT GV1.MAGV, GV1.HOTEN, GV1.NGSINH
FROM GIAOVIEN GV1
WHERE NOT EXISTS (
	SELECT CV.SOTT
	FROM CONGVIEC CV
	JOIN DETAI ON CV.MADT = DETAI.MADT
	WHERE DETAI.TENDT = N'Ứng dụng hóa học xanh'
	EXCEPT
	SELECT THAMGIADT.STT
	FROM THAMGIADT
	WHERE THAMGIADT.MAGV = GV1.MAGV
) AND EXISTS (
	SELECT THAMGIADT.MADT 
	FROM THAMGIADT 
	JOIN DETAI DT2 ON DT2.MADT = THAMGIADT.MADT
	WHERE THAMGIADT.MAGV = GV1.MAGV AND DT2.TENDT = N'Ứng dụng hóa học xanh'
)

SELECT GV1.MAGV, GV1.HOTEN, GV1.NGSINH
FROM GIAOVIEN GV1
WHERE NOT EXISTS (
	SELECT CV.SOTT
	FROM CONGVIEC CV
	JOIN DETAI ON CV.MADT = DETAI.MADT
	WHERE DETAI.TENDT = N'Ứng dụng hóa học xanh' AND NOT EXISTS(
		SELECT THAMGIADT.STT
		FROM THAMGIADT
		WHERE THAMGIADT.MAGV = GV1.MAGV AND THAMGIADT.MADT = DETAI.MADT
	)
) 
AND EXISTS (
	SELECT THAMGIADT.MADT
	FROM THAMGIADT
	JOIN DETAI ON DETAI.MADT = THAMGIADT.MADT
	WHERE THAMGIADT.MAGV = GV1.MAGV AND DETAI.TENDT = N'Ứng dụng hóa học xanh'
)

SELECT GV.MAGV, GV.HOTEN, GV.NGSINH
FROM GIAOVIEN GV
JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
JOIN DETAI DT ON TG.MADT = DT.MADT
WHERE DT.TENDT = N'Ứng dụng hóa học xanh'
GROUP BY GV.MAGV, GV.HOTEN, GV.NGSINH
HAVING COUNT(DISTINCT TG.STT) = (
    SELECT COUNT(DISTINCT CV.SOTT)
    FROM CONGVIEC CV
    JOIN DETAI DT2 ON CV.MADT = DT2.MADT
    WHERE DT2.TENDT = N'Ứng dụng hóa học xanh'
)
--Q72. Cho biết mã số, họ tên, tên bộ môn và tên người quản lý chuyên môn của giáo viên tham gia tất cả các đề tài thuộc chủ đề “Nghiên cứu phát triển”.
SELECT GV.MAGV, GV.HOTEN, BM.TENBM, GV2.HOTEN AS NguoiQuanLy
FROM GIAOVIEN GV
JOIN BOMON BM ON GV.MABM = BM.MABM
LEFT JOIN GIAOVIEN GV2 ON GV.GVQLCM = GV2.MAGV
WHERE NOT EXISTS (
    SELECT DT.MADT
    FROM DETAI DT
	JOIN CHUDE CD ON CD.MACD = DT.MACD
    WHERE CD.TENCD = N'Nghiên cứu phát triển'
    EXCEPT
    SELECT TG.MADT
    FROM THAMGIADT TG
    WHERE TG.MAGV = GV.MAGV
)

SELECT GV.MAGV, GV.HOTEN, BM.TENBM, GV2.HOTEN AS NguoiQuanLy
FROM GIAOVIEN GV
JOIN BOMON BM ON GV.MABM = BM.MABM
LEFT JOIN GIAOVIEN GV2 ON GV.GVQLCM = GV2.MAGV
WHERE NOT EXISTS (
    SELECT DT.MADT
    FROM DETAI DT
	JOIN CHUDE CD ON CD.MACD = DT.MACD
    WHERE CD.TENCD = N'Nghiên cứu phát triển'
    AND NOT EXISTS( 
		SELECT TG.MADT
		FROM THAMGIADT TG
		WHERE TG.MAGV = GV.MAGV AND TG.MADT = DT.MADT
	)
)

SELECT GV.MAGV, GV.HOTEN, BM.TENBM, GV2.HOTEN AS NguoiQuanLy
FROM GIAOVIEN GV
JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
JOIN DETAI DT ON TG.MADT = DT.MADT
JOIN CHUDE CD ON CD.MACD = DT.MACD
JOIN BOMON BM ON GV.MABM = BM.MABM
LEFT JOIN GIAOVIEN GV2 ON GV.GVQLCM = GV2.MAGV
WHERE CD.TENCD = N'Nghiên cứu phát triển'
GROUP BY GV.MAGV, GV.HOTEN, BM.TENBM, GV2.HOTEN
HAVING COUNT(DISTINCT DT.MADT) = (
    SELECT COUNT(DISTINCT DT2.MADT)
    FROM DETAI DT2
    JOIN CHUDE CD2 ON CD2.MACD = DT2.MACD
    WHERE CD2.TENCD = N'Nghiên cứu phát triển'
)